// Land border adjacency list for all countries.
// Country names match src/map/countries.ts after NAME_OVERRIDES are applied.
// Includes land borders and water crossings up to ~200 km at their nearest points,
// with three explicit exceptions noted where applicable.
// Note: Morocco borders Spain via the Ceuta/Melilla enclaves.
// Note: Russia borders Lithuania via the Kaliningrad exclave.
// Note: Azerbaijan borders Turkey via the Nakhchivan exclave.

export const borders = {
  // ── Africa ──────────────────────────────────────────────────────────────
  Algeria: [
    'Morocco',
    'Western Sahara',
    'Mauritania',
    'Mali',
    'Niger',
    'Libya',
    'Tunisia',
  ],
  Angola: ['Democratic Republic of the Congo', 'Congo', 'Zambia', 'Namibia'],
  Benin: ['Togo', 'Burkina Faso', 'Niger', 'Nigeria'],
  Botswana: ['Zambia', 'Zimbabwe', 'Namibia', 'South Africa'],
  'Burkina Faso': ['Mali', 'Niger', 'Benin', 'Togo', 'Ghana', "Côte d'Ivoire"],
  Burundi: ['Rwanda', 'Tanzania', 'Democratic Republic of the Congo'],
  'Cabo Verde': [],
  Cameroon: [
    'Nigeria',
    'Chad',
    'Central African Republic',
    'Congo',
    'Gabon',
    'Equatorial Guinea',
  ],
  'Central African Republic': [
    'Cameroon',
    'Chad',
    'Sudan',
    'South Sudan',
    'Democratic Republic of the Congo',
    'Congo',
  ],
  Chad: [
    'Libya',
    'Niger',
    'Nigeria',
    'Cameroon',
    'Central African Republic',
    'Sudan',
  ],
  Comoros: [],
  Congo: [
    'Gabon',
    'Cameroon',
    'Central African Republic',
    'Democratic Republic of the Congo',
    'Angola',
  ],
  "Côte d'Ivoire": ['Liberia', 'Guinea', 'Mali', 'Burkina Faso', 'Ghana'],
  'Democratic Republic of the Congo': [
    'Central African Republic',
    'South Sudan',
    'Uganda',
    'Rwanda',
    'Burundi',
    'Tanzania',
    'Zambia',
    'Angola',
    'Congo',
  ],
  Djibouti: ['Eritrea', 'Ethiopia', 'Somalia', 'Somaliland', 'Yemen'],
  Egypt: ['Libya', 'Sudan', 'Israel', 'Palestine'],
  'Equatorial Guinea': ['Cameroon', 'Gabon'],
  Eritrea: ['Sudan', 'Ethiopia', 'Djibouti', 'Yemen'],
  Ethiopia: [
    'Eritrea',
    'Djibouti',
    'Somalia',
    'Somaliland',
    'Kenya',
    'South Sudan',
    'Sudan',
  ],
  eSwatini: ['South Africa', 'Mozambique'],
  Gabon: ['Equatorial Guinea', 'Cameroon', 'Congo'],
  Gambia: ['Senegal'],
  Ghana: ["Côte d'Ivoire", 'Burkina Faso', 'Togo'],
  Guinea: [
    'Guinea-Bissau',
    'Senegal',
    'Mali',
    'Sierra Leone',
    'Liberia',
    "Côte d'Ivoire",
  ],
  'Guinea-Bissau': ['Senegal', 'Guinea'],
  Kenya: ['Somalia', 'Ethiopia', 'South Sudan', 'Uganda', 'Tanzania'],
  Lesotho: ['South Africa'],
  Liberia: ['Guinea', 'Sierra Leone', "Côte d'Ivoire"],
  Libya: ['Tunisia', 'Algeria', 'Niger', 'Chad', 'Sudan', 'Egypt'],
  Madagascar: ['Mozambique'], // exception: ~400 km across the Mozambique Channel
  Malawi: ['Tanzania', 'Zambia', 'Mozambique'],
  Mali: [
    'Mauritania',
    'Senegal',
    'Guinea',
    "Côte d'Ivoire",
    'Burkina Faso',
    'Niger',
    'Algeria',
  ],
  Mauritania: ['Morocco', 'Western Sahara', 'Algeria', 'Mali', 'Senegal'],
  Mauritius: [],
  Morocco: ['Algeria', 'Western Sahara', 'Mauritania', 'Spain'],
  Mozambique: [
    'Tanzania',
    'Malawi',
    'Zambia',
    'Zimbabwe',
    'South Africa',
    'eSwatini',
    'Madagascar',
  ],
  Namibia: ['Angola', 'Zambia', 'Botswana', 'South Africa'],
  Niger: [
    'Algeria',
    'Mali',
    'Burkina Faso',
    'Benin',
    'Nigeria',
    'Chad',
    'Libya',
  ],
  Nigeria: ['Niger', 'Chad', 'Cameroon', 'Benin'],
  Rwanda: ['Uganda', 'Tanzania', 'Burundi', 'Democratic Republic of the Congo'],
  'São Tomé and Principe': [],
  Senegal: ['Mauritania', 'Gambia', 'Guinea-Bissau', 'Guinea', 'Mali'],
  Seychelles: [],
  'Sierra Leone': ['Guinea', 'Liberia'],
  Somalia: ['Djibouti', 'Ethiopia', 'Kenya', 'Somaliland'],
  Somaliland: ['Ethiopia', 'Djibouti', 'Somalia'],
  'South Africa': [
    'Namibia',
    'Botswana',
    'Zimbabwe',
    'Mozambique',
    'eSwatini',
    'Lesotho',
  ],
  'South Sudan': [
    'Sudan',
    'Ethiopia',
    'Kenya',
    'Uganda',
    'Democratic Republic of the Congo',
    'Central African Republic',
  ],
  Sudan: [
    'Egypt',
    'Libya',
    'Chad',
    'Central African Republic',
    'South Sudan',
    'Ethiopia',
    'Eritrea',
  ],
  Tanzania: [
    'Kenya',
    'Uganda',
    'Rwanda',
    'Burundi',
    'Democratic Republic of the Congo',
    'Zambia',
    'Malawi',
    'Mozambique',
  ],
  Togo: ['Ghana', 'Burkina Faso', 'Benin'],
  Tunisia: ['Algeria', 'Libya'],
  Uganda: [
    'Kenya',
    'South Sudan',
    'Democratic Republic of the Congo',
    'Rwanda',
    'Tanzania',
  ],
  'Western Sahara': ['Morocco', 'Algeria', 'Mauritania'],
  Zambia: [
    'Angola',
    'Democratic Republic of the Congo',
    'Tanzania',
    'Malawi',
    'Mozambique',
    'Zimbabwe',
    'Botswana',
    'Namibia',
  ],
  Zimbabwe: ['Zambia', 'Botswana', 'Mozambique', 'South Africa'],

  // ── Europe ──────────────────────────────────────────────────────────────
  Albania: ['Montenegro', 'Kosovo', 'Macedonia', 'Greece'],
  Andorra: ['Spain', 'France'],
  Austria: [
    'Germany',
    'Switzerland',
    'Liechtenstein',
    'Italy',
    'Slovenia',
    'Hungary',
    'Slovakia',
    'Czechia',
  ],
  Belarus: ['Lithuania', 'Latvia', 'Russia', 'Ukraine', 'Poland'],
  Belgium: ['France', 'Luxembourg', 'Germany', 'Netherlands'],
  'Bosnia and Herzegovina': ['Croatia', 'Serbia', 'Montenegro'],
  Bulgaria: ['Romania', 'Serbia', 'Macedonia', 'Greece', 'Turkey'],
  Croatia: [
    'Slovenia',
    'Hungary',
    'Serbia',
    'Bosnia and Herzegovina',
    'Montenegro',
  ],
  Cyprus: ['Northern Cyprus', 'Turkey', 'Lebanon', 'Syria'], // ~75 km from Turkey, ~100 km from Syria, ~175 km from Lebanon
  Czechia: ['Germany', 'Austria', 'Slovakia', 'Poland'],
  Denmark: ['Germany', 'Sweden'],
  Estonia: ['Latvia', 'Russia'],
  Finland: ['Sweden', 'Norway', 'Russia'],
  France: [
    'Spain',
    'Andorra',
    'Monaco',
    'Italy',
    'Switzerland',
    'Germany',
    'Luxembourg',
    'Belgium',
    'United Kingdom',
  ],
  Germany: [
    'France',
    'Luxembourg',
    'Belgium',
    'Netherlands',
    'Denmark',
    'Poland',
    'Czechia',
    'Austria',
    'Switzerland',
  ],
  Greece: ['Bulgaria', 'Macedonia', 'Albania', 'Turkey'],
  Greenland: ['Canada', 'Iceland'], // exception: ~290 km to Iceland
  Hungary: [
    'Austria',
    'Slovakia',
    'Ukraine',
    'Romania',
    'Serbia',
    'Croatia',
    'Slovenia',
  ],
  Iceland: ['Greenland'], // exception: ~290 km to Greenland
  Ireland: ['United Kingdom'],
  Italy: [
    'France',
    'Switzerland',
    'Austria',
    'Slovenia',
    'San Marino',
    'Vatican',
    'Malta',
  ],
  Kosovo: ['Serbia', 'Macedonia', 'Albania', 'Montenegro'],
  Latvia: ['Estonia', 'Lithuania', 'Belarus', 'Russia'],
  Liechtenstein: ['Switzerland', 'Austria'],
  Lithuania: ['Latvia', 'Belarus', 'Poland', 'Russia'],
  Luxembourg: ['France', 'Belgium', 'Germany'],
  Macedonia: ['Bulgaria', 'Serbia', 'Kosovo', 'Albania', 'Greece'],
  Malta: ['Italy'], // Tunisia is ~290 km away
  Moldova: ['Ukraine', 'Romania'],
  Monaco: ['France'],
  Montenegro: [
    'Croatia',
    'Bosnia and Herzegovina',
    'Serbia',
    'Kosovo',
    'Albania',
  ],
  Netherlands: ['Belgium', 'Germany'],
  'Northern Cyprus': ['Cyprus', 'Turkey', 'Lebanon', 'Syria'], // ~75 km from Turkey, ~100 km from Syria, ~175 km from Lebanon
  Norway: ['Sweden', 'Finland', 'Russia'],
  Poland: [
    'Germany',
    'Czechia',
    'Slovakia',
    'Ukraine',
    'Belarus',
    'Lithuania',
    'Russia',
  ],
  Portugal: ['Spain'],
  Romania: ['Ukraine', 'Moldova', 'Hungary', 'Serbia', 'Bulgaria'],
  Russia: [
    'Norway',
    'Finland',
    'Estonia',
    'Latvia',
    'Lithuania',
    'Belarus',
    'Ukraine',
    'Georgia',
    'Azerbaijan',
    'Kazakhstan',
    'China',
    'Mongolia',
    'North Korea',
    'Japan',
    'Poland',
    'United States of America',
  ],
  'San Marino': ['Italy'],
  Serbia: [
    'Hungary',
    'Romania',
    'Bulgaria',
    'Macedonia',
    'Kosovo',
    'Bosnia and Herzegovina',
    'Montenegro',
    'Croatia',
  ],
  Slovakia: ['Czechia', 'Austria', 'Hungary', 'Ukraine', 'Poland'],
  Slovenia: ['Austria', 'Italy', 'Hungary', 'Croatia'],
  Spain: ['Portugal', 'France', 'Andorra', 'Morocco'],
  Sweden: ['Norway', 'Finland', 'Denmark'],
  Switzerland: ['France', 'Germany', 'Austria', 'Liechtenstein', 'Italy'],
  Ukraine: [
    'Poland',
    'Slovakia',
    'Hungary',
    'Romania',
    'Moldova',
    'Russia',
    'Belarus',
  ],
  'United Kingdom': ['Ireland', 'France'],
  Vatican: ['Italy'],

  // ── Middle East ─────────────────────────────────────────────────────────
  Bahrain: ['Saudi Arabia'],
  Iraq: ['Turkey', 'Syria', 'Jordan', 'Saudi Arabia', 'Kuwait', 'Iran'],
  Israel: ['Egypt', 'Palestine', 'Jordan', 'Lebanon', 'Syria'],
  Jordan: ['Saudi Arabia', 'Iraq', 'Syria', 'Israel', 'Palestine'],
  Kuwait: ['Saudi Arabia', 'Iraq'],
  Lebanon: ['Syria', 'Israel', 'Cyprus', 'Northern Cyprus'],
  Oman: ['United Arab Emirates', 'Saudi Arabia', 'Yemen'],
  Palestine: ['Egypt', 'Israel', 'Jordan'],
  Qatar: ['Saudi Arabia'],
  'Saudi Arabia': [
    'Jordan',
    'Iraq',
    'Kuwait',
    'Qatar',
    'United Arab Emirates',
    'Oman',
    'Yemen',
    'Bahrain',
  ],
  Syria: [
    'Turkey',
    'Iraq',
    'Jordan',
    'Lebanon',
    'Israel',
    'Cyprus',
    'Northern Cyprus',
  ],
  'United Arab Emirates': ['Saudi Arabia', 'Oman'],
  Yemen: ['Saudi Arabia', 'Oman', 'Djibouti', 'Eritrea'],

  // ── Central & South Asia ────────────────────────────────────────────────
  Afghanistan: [
    'Iran',
    'Turkmenistan',
    'Uzbekistan',
    'Tajikistan',
    'China',
    'Pakistan',
  ],
  Armenia: ['Turkey', 'Georgia', 'Azerbaijan', 'Iran'],
  Azerbaijan: ['Russia', 'Georgia', 'Armenia', 'Iran', 'Turkey'],
  Bangladesh: ['India', 'Myanmar'],
  Bhutan: ['India', 'China'],
  Georgia: ['Russia', 'Turkey', 'Armenia', 'Azerbaijan'],
  India: [
    'Pakistan',
    'China',
    'Nepal',
    'Bhutan',
    'Bangladesh',
    'Myanmar',
    'Sri Lanka',
    'Maldives',
  ],
  Iran: [
    'Turkey',
    'Iraq',
    'Azerbaijan',
    'Turkmenistan',
    'Afghanistan',
    'Pakistan',
    'Armenia',
  ],
  Kazakhstan: ['Russia', 'China', 'Kyrgyzstan', 'Uzbekistan', 'Turkmenistan'],
  Kyrgyzstan: ['Kazakhstan', 'China', 'Tajikistan', 'Uzbekistan'],
  Maldives: ['India', 'Sri Lanka'],
  Nepal: ['India', 'China'],
  Pakistan: ['Iran', 'Afghanistan', 'China', 'India'],
  'Sri Lanka': ['India', 'Maldives'],
  Tajikistan: ['Kyrgyzstan', 'Uzbekistan', 'Afghanistan', 'China'],
  Turkey: [
    'Greece',
    'Bulgaria',
    'Georgia',
    'Armenia',
    'Azerbaijan',
    'Iran',
    'Iraq',
    'Syria',
    'Cyprus',
    'Northern Cyprus',
  ],
  Turkmenistan: ['Kazakhstan', 'Uzbekistan', 'Afghanistan', 'Iran'],
  Uzbekistan: [
    'Kazakhstan',
    'Kyrgyzstan',
    'Tajikistan',
    'Afghanistan',
    'Turkmenistan',
  ],

  // ── East Asia ───────────────────────────────────────────────────────────
  China: [
    'Russia',
    'Mongolia',
    'Kazakhstan',
    'Kyrgyzstan',
    'Tajikistan',
    'Afghanistan',
    'Pakistan',
    'India',
    'Nepal',
    'Bhutan',
    'Myanmar',
    'Laos',
    'Vietnam',
    'North Korea',
    'Hong Kong',
    'Macao',
    'Taiwan',
  ],
  'Hong Kong': ['China'],
  Japan: ['South Korea', 'Russia'],
  Macao: ['China'],
  Mongolia: ['Russia', 'China'],
  'North Korea': ['Russia', 'China', 'South Korea'],
  'South Korea': ['North Korea', 'Japan'],
  Taiwan: ['China'], // Philippines is ~400 km away

  // ── Southeast Asia ──────────────────────────────────────────────────────
  Brunei: ['Malaysia'],
  Cambodia: ['Vietnam', 'Laos', 'Thailand'],
  Indonesia: ['Malaysia', 'Papua New Guinea', 'Timor-Leste', 'Philippines'],
  Laos: ['China', 'Vietnam', 'Cambodia', 'Thailand', 'Myanmar'],
  Malaysia: ['Thailand', 'Brunei', 'Indonesia', 'Philippines', 'Singapore'],
  Myanmar: ['China', 'Laos', 'Thailand', 'Bangladesh', 'India'],
  Philippines: ['Malaysia', 'Indonesia'], // Taiwan is ~400 km away
  Singapore: ['Malaysia'],
  Thailand: ['Myanmar', 'Laos', 'Cambodia', 'Malaysia'],
  'Timor-Leste': ['Indonesia'],
  Vietnam: ['China', 'Laos', 'Cambodia'],

  // ── Oceania ─────────────────────────────────────────────────────────────
  Australia: ['Papua New Guinea', 'New Zealand'], // exception: ~2200 km to New Zealand
  Fiji: [],
  Kiribati: [],
  'Marshall Islands': [],
  Micronesia: [],
  Nauru: [],
  'New Zealand': ['Australia'], // exception: ~2200 km to Australia
  Palau: [],
  'Papua New Guinea': ['Indonesia', 'Australia', 'Solomon Islands'],
  Samoa: [],
  'Solomon Islands': ['Papua New Guinea'],
  Tonga: [],
  Vanuatu: [],

  // ── Americas ────────────────────────────────────────────────────────────
  // North America
  Canada: ['United States of America', 'Greenland'],
  Mexico: ['United States of America', 'Guatemala', 'Belize'],
  'United States of America': ['Canada', 'Mexico', 'Bahamas', 'Russia'],

  // Caribbean
  'Antigua and Barbuda': ['Dominica', 'Saint Kitts and Nevis'],
  Bahamas: ['Cuba', 'United States of America'],
  Barbados: ['Grenada', 'Saint Vincent and the Grenadines', 'Saint Lucia'],
  Cuba: ['Haiti', 'Jamaica', 'Bahamas'],
  Dominica: ['Saint Lucia', 'Antigua and Barbuda'],
  'Dominican Republic': ['Haiti', 'Puerto Rico'],
  Grenada: [
    'Trinidad and Tobago',
    'Saint Vincent and the Grenadines',
    'Barbados',
  ],
  Haiti: ['Dominican Republic', 'Cuba', 'Jamaica'],
  Jamaica: ['Cuba', 'Haiti'],
  'Puerto Rico': ['Dominican Republic'],
  'Saint Kitts and Nevis': ['Antigua and Barbuda'],
  'Saint Lucia': ['Saint Vincent and the Grenadines', 'Barbados', 'Dominica'],
  'Saint Vincent and the Grenadines': ['Grenada', 'Barbados', 'Saint Lucia'],
  'Trinidad and Tobago': ['Venezuela', 'Grenada'],

  // Central America
  Belize: ['Mexico', 'Guatemala'],
  'Costa Rica': ['Nicaragua', 'Panama'],
  'El Salvador': ['Guatemala', 'Honduras'],
  Guatemala: ['Mexico', 'Belize', 'Honduras', 'El Salvador'],
  Honduras: ['Guatemala', 'El Salvador', 'Nicaragua'],
  Nicaragua: ['Honduras', 'Costa Rica'],
  Panama: ['Costa Rica', 'Colombia'],

  // South America
  Argentina: ['Chile', 'Bolivia', 'Paraguay', 'Brazil', 'Uruguay'],
  Bolivia: ['Peru', 'Brazil', 'Paraguay', 'Argentina', 'Chile'],
  Brazil: [
    'Venezuela',
    'Guyana',
    'Suriname',
    'French Guiana',
    'Colombia',
    'Peru',
    'Bolivia',
    'Paraguay',
    'Argentina',
    'Uruguay',
  ],
  Chile: ['Peru', 'Bolivia', 'Argentina'],
  Colombia: ['Panama', 'Venezuela', 'Ecuador', 'Peru', 'Brazil'],
  Ecuador: ['Colombia', 'Peru'],
  'French Guiana': ['Suriname', 'Brazil'],
  Guyana: ['Venezuela', 'Suriname', 'Brazil'],
  Paraguay: ['Brazil', 'Bolivia', 'Argentina'],
  Peru: ['Ecuador', 'Colombia', 'Brazil', 'Bolivia', 'Chile'],
  Suriname: ['Guyana', 'Brazil', 'French Guiana'],
  Uruguay: ['Argentina', 'Brazil'],
  Venezuela: ['Colombia', 'Guyana', 'Brazil', 'Trinidad and Tobago'],
} as Record<string, string[]>;
